### ISSUE TITLE
A lot of white space 

### ISSUE THREAD

**Issue by hsauro** [sys-bio/SBMLDiagrams#15]
The following script generates an image with a lot of white space.  can we remove the white space?

import SBMLDiagrams
import tellurium as te
r = te.loada ('''
A -> B; k1*A; 
B -> C; k2*B 
k1 = 0.1; k2 = 0.2;
A = 10
''')

df = SBMLDiagrams.load(r.getSBML())
df.autolayout(layout="spring")
df.draw([500,500])

![image](https://user-images.githubusercontent.com/1054990/160677309-3ba81ece-e392-4e74-b997-215d4125305d.png)

**Comment by SunnyXu** [comment]
There is white space because you force the imageSize to be [500,500]. It has fitted the network to either the length of width or height. if you just do draw(), there will be no white space.
