### ISSUE TITLE
Change the way output format is set

### ISSUE THREAD

**Issue by hsauro** [sys-bio/SBMLDiagrams#16]
Currently to set the output format to pdf one has to do:

df.draw([500,500],output_fileName='myfile', fileFormat='PDF')

It would be better if a user could user a simpler form:

df.draw([500,500],output_fileName='myfile.pdf')

and the code would automatically recognize that the output should be a pdf file from the file extension.

Note also that fileFormat is case sensitive, if I use fileFormat='pdf' there is no output or error message. The string has to be upper case 'PDF'.

**Comment by SunnyXu** [comment]
changed to df.draw(output_fileName='myfile.png')
