### ISSUE TITLE
Ensure that models can be moved from coyte to sbmldiagram without issue

### ISSUE THREAD

**Issue by hsauro** [sys-bio/SBMLDiagrams#22]
I noticed a couple of instances where models generated using coyote don't draw correctly in SBMLDragrams.  I can't upload the XML model to Github so instead, I changed the extension to csv. You need to change the extension back to XML to load them. There obviously needs to be a lot more testing before we can submit the manuscript. 

[cycle1_xml..csv](https://github.com/sys-bio/SBMLDiagrams/files/8375107/cycle1_xml.csv)
[branch1_xml.csv](https://github.com/sys-bio/SBMLDiagrams/files/8375110/branch1_xml.csv)
[branch2_xml.csv](https://github.com/sys-bio/SBMLDiagrams/files/8375112/branch2_xml.csv)

**Comment by SunnyXu** [comment]
1) I have fixed the exportSBML plugin in coyote to make sure it works for a reaction with straight line. Details see the commit (https://github.com/samuels342/PyRKViewer-Plugins/commit/472d22da7e33f74f98530cbb6dfa7662914e4dcd). So the cycle1 and branch1 should work now.
2) you can exchange branch2 between coyote and sbmldiagrams, they look the same now.
