### ISSUE TITLE
Setting setNodeBorderWidsth generates a table as output

### ISSUE THREAD

**Issue by hsauro** [sys-bio/SBMLDiagrams#23]
Calling setNodeBorderWidth at the console generates the following output which is of no interest to the user. setNodeBorderWidth should return nothing. This may apply to other methods as well, if so this issue applies to them as well. 

df.setNodeBorderWidth('pyruvate', 5)

(   net_idx  idx  ...          border_color border_width
 0        0    0  ...  [255, 255, 255, 255]          2.0
 1        0    1  ...  [255, 255, 255, 255]          2.0
 
 [2 rows x 8 columns],
     net_idx  comp_idx  idx  ...  shape_name shape_type shape_info
 0         0         1    0  ...   rectangle  rectangle         []
 1         0         1    1  ...   rectangle  rectangle         []
 2         0         1    2  ...   rectangle  rectangle         []
 3         0         1    3  ...   rectangle  rectangle         []
 4         0         1    4  ...   rectangle  rectangle         []
 5         0         1    5  ...   rectangle  rectangle         []
 6         0         1    6  ...   rectangle  rectangle         []
 7         0         1    7  ...   rectangle  rectangle         []
 8         0         1    8  ...   rectangle  rectangle         []
 9         0         1    9  ...   rectangle  rectangle         []
 10        0         1   10  ...   rectangle  rectangle         []
 11        0         1   11  ...   rectangle  rectangle         []
 12        0         1   12  ...   rectangle  rectangle         []
 13        0         1   13  ...   rectangle  rectangle         []
 14        0         1   14  ...   rectangle  rectangle         []
 15        0         1   15  ...   rectangle  rectangle         []
 16        0         1   16  ...   rectangle  rectangle         []
 17        0         1   17  ...   rectangle  rectangle         []
 18        0         1   18  ...   rectangle  rectangle         []
 19        0         1   19  ...   rectangle  rectangle         []
 20        0         1   20  ...   rectangle  rectangle         []
 21        0         1   21  ...   rectangle  rectangle         []
 22        0         1   22  ...   rectangle  rectangle         []
 
 [23 rows x 21 columns],
     net_idx  idx   id  ... arrow_head_size rxn_dash rxn_reversible
 0         0    0   J0  ...    [12.0, 15.0]       []           True
 1         0    1   J1  ...    [12.0, 15.0]       []           True
 2         0    2   J2  ...    [12.0, 15.0]       []           True
 3         0    3   J3  ...    [12.0, 15.0]       []           True
 4         0    4   J4  ...    [12.0, 15.0]       []           True
 5         0    5   J5  ...    [12.0, 15.0]       []           True
 6         0    6   J6  ...    [12.0, 15.0]       []           True
 7         0    7   J7  ...    [12.0, 15.0]       []           True
 8         0    8   J8  ...    [12.0, 15.0]       []           True
 9         0    9   J9  ...    [12.0, 15.0]       []           True
 10        0   10  J10  ...    [12.0, 15.0]       []           True
 
 [11 rows x 15 columns],
 Empty DataFrame
 Columns: [txt_content, txt_position, txt_size, txt_font_color, txt_line_width, txt_font_size]
 Index: [],
 Empty DataFrame
 Columns: [shape_name, position, size, fill_color, border_color, border_width, shape_type, shape_info]
 Index: [])

**Comment by SunnyXu** [comment]
fixed all the relevant functions

**Comment by SunnyXu** [comment]
details see the commit ([fixed all the relevant functions](https://github.com/SunnyXu/SBMLDiagrams/commit/f13a4b9f7f8a17744808ae291e158266b816515d))
