### ISSUE TITLE
White space around network

### ISSUE THREAD

**Issue by hsauro** [sys-bio/SBMLDiagrams#27]
There is still a lot of white space around networks, in the following case, there is a large area of white to the right of the pathway.

![image](https://user-images.githubusercontent.com/1054990/162842308-83f9f142-e6b6-401d-9800-4232edf1f881.png)

r2 = te.loada ('''
     S1 -> S2; v;
     S2 -> S3; v;
     S2 -> S4; v
     S4 -> S5; v;
     S4 -> S2; v;
     v = 1
''')

la  = SBMLDiagrams.load (r2.getSBML())
la.autolayout(layout="spring")
la.draw(setImageSize=[400,400])

**Comment by SunnyXu** [comment]
pls see issue 15
