### ISSUE TITLE
Create a SBGN example

### ISSUE THREAD

**Issue by hsauro** [sys-bio/SBMLDiagrams#5]
Create a SBGN example, eg

Try this one first:

![image](https://user-images.githubusercontent.com/1054990/156837312-96fefc81-1e9d-4ce0-81d7-6563c816359a.png)

![image](https://user-images.githubusercontent.com/1054990/156836981-8c40cc27-8dff-4eab-bb32-cf2f1be6f30e.png)

**Comment by SunnyXu** [comment]
a comparable example is available at github (https://github.com/sys-bio/SBMLDiagrams/tree/main/examples/Interface_to_SBGN).
