### ISSUE TITLE
Add four more triangles to the shape options

### ISSUE THREAD

**Issue by hsauro** [sys-bio/SBMLDiagrams#6]
Add four more triangles to the shape options. The names can match CSS shapes:

upTriangle
downTriangle
leftTriangle
rightTriangle

See

https://fellowtuts.com/html-css/css-shapes-triangle/

![image](https://user-images.githubusercontent.com/1054990/156853669-c4dbca61-94e4-40ad-aab1-730b3093535f.png)

**Comment by SunnyXu** [comment]
new api shape options have been added. details see (https://sunnyxu.github.io/SBMLDiagrams/processSBML.html#SBMLDiagrams.processSBML.load.setNodeShape).
