### ISSUE TITLE
Add node text alignment options

### ISSUE THREAD

**Issue by hsauro** [sys-bio/SBMLDiagrams#7]
Add node text alignment option. Allow users to specify the alignment of text within a node:

center
leftCenter
rightCenter
upperCenter
lowerCenter
upperLeft
upperRight
lowerLeft
rightLeft
userDefined

**Comment by SunnyXu** [comment]
nine api functions have been added. Details see (https://sunnyxu.github.io/SBMLDiagrams/processSBML.html#SBMLDiagrams.processSBML.load.setNodeTextPositionCenter).
