### ISSUE TITLE
Add method to specifiy coordinates for polygon

### ISSUE THREAD

**Issue by hsauro** [sys-bio/SBMLDiagrams#8]
Allow a user to specify an arbitrary shape by specifying a polygon, eg

la.defineShape ("name of polygon", [[x1,y1], [x2, y2], [x3, y3], ..... etc ]])

la.setNodeShape ("name of polygon", scale = value)

It might be better for a user to define the polygon coordinates using normalized coordinates that for from 0 -> 1, then you can move and scale that into position.

eg

a square would be defined as:

la.defineShape ('mysquare', [[0, 0], [0, 1], [1, 1], [1, 0], [0,0]])

**Comment by SunnyXu** [comment]
new api setNodeArbitraryPolygonShape(). details see (https://sunnyxu.github.io/SBMLDiagrams/processSBML.html#SBMLDiagrams.processSBML.load.setNodeArbitraryPolygonShape)
